// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxX45fhsmW59sVdVRJyhUoyhtZCA_bvs8',
    appId: '1:696805224619:web:0a4e9f3c4a4784adf147ee',
    messagingSenderId: '696805224619',
    projectId: 'ithera-4bb28',
    authDomain: 'ithera-4bb28.firebaseapp.com',
    storageBucket: 'ithera-4bb28.firebasestorage.app',
    measurementId: 'G-GJ6RWSQLWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbZBbKUHTVSCBYwXDPF3hcI3qgxx767nk',
    appId: '1:696805224619:android:701067277677441af147ee',
    messagingSenderId: '696805224619',
    projectId: 'ithera-4bb28',
    storageBucket: 'ithera-4bb28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcDloGJGTOy6j32tgwH3p8c5__wYMDn70',
    appId: '1:696805224619:ios:37b9a38d1f825ee1f147ee',
    messagingSenderId: '696805224619',
    projectId: 'ithera-4bb28',
    storageBucket: 'ithera-4bb28.firebasestorage.app',
    iosBundleId: 'com.ithera.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcDloGJGTOy6j32tgwH3p8c5__wYMDn70',
    appId: '1:696805224619:ios:d421013262d5c400f147ee',
    messagingSenderId: '696805224619',
    projectId: 'ithera-4bb28',
    storageBucket: 'ithera-4bb28.firebasestorage.app',
    iosBundleId: 'com.example.itheraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxX45fhsmW59sVdVRJyhUoyhtZCA_bvs8',
    appId: '1:696805224619:web:47fe15ff77b852a1f147ee',
    messagingSenderId: '696805224619',
    projectId: 'ithera-4bb28',
    authDomain: 'ithera-4bb28.firebaseapp.com',
    storageBucket: 'ithera-4bb28.firebasestorage.app',
    measurementId: 'G-B3226SXNL3',
  );
}
